---

Description: S3 bucket
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  AccessControl:
    Description: Access control for bucket
    Type: String
    Default: Private

  ConfigBucket:
    Description: Environment name
    Type: String

  Versioning:
    Description: Versioning for bucket
    Type: String
    Default: Enabled

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: !Ref AccessControl
      BucketName: !Ref ConfigBucket
      VersioningConfiguration:
        Status: !Ref Versioning
