---

# global shortcuts
env: &ENV training
config_bucket: "config.{{ env }}.nhsd.io"
public_fqdn: &FQDN training.nhsd.io

aws:
  tags:
    Project: Digital Website
    Environment: *ENV

ondemand:
  public_fqdn: nhsd.io
  hosted_zone_id: Z37KMFR2PGJ2AX
  bloomreach_environment: training
  with_cloudfront: disabled
  files_host: files.training.nhsd.io

aws_permissions:
  files_bucket_name: files.training.nhsd.io
