---

- name: Config Bucket
  cloudformation:
    stack_name: "{{ env }}-config"
    state: present
    template: "{{ role_path }}/files/bucket.yml"
    template_parameters:
      ConfigBucket: "{{ config_bucket }}"
