---

Parameters:
  Environment:
    Description: Environment Name
    Type: String

  BloomreachEnvironment:
    Description: BloomReach OnDemand Environment Name
    Type: String

  HostedZoneId:
    Description: Hosted Zone Id
    Type: String

  HostedDomain:
    Description: Public root domain name
    Type: String

Resources:
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: !Sub "${Environment} Hippo Site"
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "${Environment}.${HostedDomain}"
      TTL: 300
      Type: CNAME
      ResourceRecords:
        - !Sub "www.nhs.${BloomreachEnvironment}.onehippo.com"

  CmsDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: !Sub "${Environment} Hippo CMS"
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "cms-${Environment}.${HostedDomain}"
      TTL: 300
      Type: CNAME
      ResourceRecords:
        - !Sub "cms-nhs.${BloomreachEnvironment}.onehippo.com"

  ContentDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Comment: !Sub "${Environment} Hippo Content site domain"
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "content.${Environment}.${HostedDomain}"
      TTL: 300
      Type: CNAME
      ResourceRecords:
        - !Sub "${Environment}.${HostedDomain}"
