---

# global shortcuts
env: &ENV dev
config_bucket: "config.{{ env }}.digital.nhs.uk"
public_fqdn: &FQDN dev.ps.digital.nhs.uk

aws:
  tags:
    Project: Publication Service
    Environment: *ENV

aws_cd:
  public_fqdn: digital.nhs.uk
  pipelines:
    build:
      enabled: yes
      vpc_id: vpc-65b45401
      subnet_id: subnet-543af230

aws_foundation:
  environment_name: *ENV
  public_fqdn:
    - *FQDN

hippo_authoring:
  mysql:
    host: hippo-authoring.mysql.db.int
    root_user: root
    user: hippocms
    dbname: hippocms
