---

# global shortcuts
env: &ENV dev
config_bucket: "config.{{ env }}.nhsd.io"
public_fqdn: &FQDN dev.nhsd.io

aws:
  tags:
    Project: Digital Website
    Environment: *ENV

aws_foundation:
  environment_name: *ENV
  public_fqdn:
    - *FQDN

ondemand:
  public_fqdn: nhsd.io
  hosted_zone_id: Z37KMFR2PGJ2AX
  bloomreach_environment: dev
  with_cloudfront: disabled
  files_host: files.dev.nhsd.io

aws_permissions:
  files_bucket_name: files.dev.nhsd.io
