---

# global shortcuts
env: &ENV dev
config_bucket: "config.{{ env }}.ps.nhsd.io"
public_fqdn: &FQDN dev.ps.nhsd.io

aws:
  tags:
    Project: Publication Service
    Environment: *ENV

aws_ondemand:
  public_fqdn: nhsd.io
  hosted_zone_id: Z37KMFR2PGJ2AX

aws_cd:
  public_fqdn: nhsd.io
  pipelines:
    build:
      enabled: yes
      vpc_id: vpc-65b45401
      subnet_id: subnet-543af230

aws_foundation:
  environment_name: *ENV
  public_fqdn:
    - *FQDN

hippo_authoring:
  mysql:
    host: hippo-authoring.mysql.db.int
    root_user: root
    user: hippocms
    dbname: hippocms
