---
# Manage CloudFormation stack

- name: Manage CF Stack
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Assert global variable are set
      assert:
        that:
          - env is defined
          - role is defined

    - name: Assert AWS SSH key name
      assert:
        that:
          - lookup('env','AWS_KEY_NAME')
      when: role in [ 'bastion', 'hippo_authoring', 'hippo_delivery' ]

    - name: Load deploy artefact
      include_vars: "{{ playbook_dir }}/../../.artefacts/{{ role }}.yml"
      when: role in [ 'bastion', 'hippo_authoring', 'hippo_delivery' ]

    - name: Set basic environment variables
      set_fact:
        environment_vars:
          env: "{{ env }}"

    - name: Add role environment variables
      set_fact:
        environment_vars: "{{ environment_vars | combine({ role: vars[role] | default({}) }, recursive=True) }}"

  roles:
    - role: "{{ role }}"
